### ISSUE TITLE
Wybór jezyka programowania PC

### ISSUE THREAD

**Issue by kleszczagh** [kleszczagh/Stacja_Multimedialna#2]

**Comment by mcksyrek** [comment]
zapoznając się z dokumentacją poszczególnych języków: C/C++, JavaScript, Python, C#, Java proponuję wykorzystanie do naszego projektu C/C++ z uwagi na uniwersalność, zarówno w komunikacji z serwerem pogodowym, jak i w przekazywaniu poleceń do mikrokontrolera.

**Comment by wojciechbodo** [comment]
Zgadzam się co do wyboru języka C/C++. Poza uniwersalnością jego zaletą jest to że wszyscy go znamy.

**Comment by wojciechbodo** [comment]
Skoro nikt nie ma żadnych sprzeciwów wobec języka C++ postanowiłem że użyjemy właśnie jego
