### ISSUE TITLE
Rozwiązanie problemu otwarcia i wykorzystania portu COM w PC

### ISSUE THREAD

**Issue by kleszczagh** [kleszczagh/Stacja_Multimedialna#22]

**Comment by wojciechbodo** [comment]
Rozpoczęcie pracy nad algorytmem blokowym

**Comment by wojciechbodo** [comment]
Zakończenie pracy nad algorytmem blokowym.

**Comment by wojciechbodo** [comment]
Znalezienie odpowiedniej biblioteki oraz testowanie jej

**Comment by wojciechbodo** [comment]
utworzenie programu wysyłającego testowe dane przez port com

**Comment by wojciechbodo** [comment]
ukończenie prototypu programy wysyłającego dane przez port com
