### ISSUE TITLE
Program na PC

### ISSUE THREAD

**Issue by jaqb96** [kleszczagh/Stacja_Multimedialna#6]

**Comment by mcksyrek** [comment]
Zapoznanie się z biblioteką netlib jako z potencjalnym rozwiązaniem.

**Comment by mcksyrek** [comment]
Przegląd serwisów pogodowych, których wykorzystanie w projekcie jest rozważane

**Comment by mcksyrek** [comment]
Zapoznanie się z działaniem serwisów pogodowych pod kątem pobierania danych

**Comment by mcksyrek** [comment]
Rozpoczęcie pracy nad programem. Rozpoczęcie praktycznego rozpoznania używanej technologii.

**Comment by mcksyrek** [comment]
Kontynuacja pracy nad programem.
