### ISSUE TITLE
Stworzenie ogólnego algorytmu blokowego

### ISSUE THREAD

**Issue by jaqb96** [kleszczagh/Stacja_Multimedialna#7]

**Comment by wojciechbodo** [comment]
Rozpoczęcie prac nad algorytmem blokowym

**Comment by wojciechbodo** [comment]
zapoznanie się z zasadami tworzenia algorytmów blokowych

**Comment by wojciechbodo** [comment]
zapoznanie się z metodami tworzenia algorytmów blokowych

**Comment by wojciechbodo** [comment]
wybranie programu do tworzenia algorytmu (algorytm.org)

**Comment by wojciechbodo** [comment]
Zakończenie pracy nad algorytmem blokowym
